# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- przgen
variables:
  SECRET_KEY: $(SECRET_KEY)
  DATABASE_URI: $(DATABASE_URI)
pool:
  name: Azure Pipelines
#Your build pipeline references an undefined variable named ‘DATABASE_URI’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘SECRET_KEY’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘DATABASE_URI’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘SECRET_KEY’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘MYSQL_ROOT_PASSWORD’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘DBUser’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘DBserv’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- bash: |
   # Write your commands here
   mv routes.py temp
   sed -e "s,('http://txtgen:8000/text'),('https://textgen.azurewebsites.net/text'),g" -e "s,('http://numgen:8000/num'),('https://numgene.azurewebsites.net/num'),g" temp > routes.py
   
  workingDirectory: przgen/application
  displayName: 'Edit przgen routes.py'

- bash: |
   # Write your commands here
   mv routes.py temp
   sed -e "s,('http://przgen:8000/home'),('https://prize.azurewebsites.net/home'),g" temp > routes.py
   
  workingDirectory: prize/application
  displayName: 'Edit prize routes.py '

- task: Docker@2
  displayName: 'buildAndPush Text Generator copy'
  inputs:
    containerRegistry: GroupProject
    repository: elsahib20/txtgen:$(Build.BuildId)
    Dockerfile: txtgen/Dockerfile

- task: Docker@2
  displayName: 'buildAndPush Prize Application copy'
  inputs:
    containerRegistry: GroupProject
    repository: elsahib20/prize:$(Build.BuildId)
    Dockerfile: prize/Dockerfile

- task: Docker@2
  displayName: 'buildAndPush Prize Generator copy'
  inputs:
    containerRegistry: GroupProject
    repository: elsahib20/przgen:$(Build.BuildId)
    Dockerfile: przgen/Dockerfile

- task: Docker@2
  displayName: 'buildAndPush Number Generator copy'
  inputs:
    containerRegistry: GroupProject
    repository: elsahib20/numgen:$(Build.BuildId)
    Dockerfile: numgen/Dockerfile

- task: AzureFunctionAppContainer@1
  displayName: 'Azure Function App on Container Deploy: textgen'
  inputs:
    azureSubscription: 'Free Trial (7f34fecc-80ca-417b-9aae-80ddc33a2d4b)'
    appName: textgen
    imageName: 'elsahib20/txtgen:$(Build.BuildId)'

- task: AzureFunctionAppContainer@1
  displayName: 'Azure Function App on Container Deploy: numgen'
  inputs:
    azureSubscription: 'Free Trial (7f34fecc-80ca-417b-9aae-80ddc33a2d4b)'
    appName: numgene
    imageName: 'elsahib20/numgen:$(Build.BuildId)'

- task: AzureFunctionAppContainer@1
  displayName: 'Azure Function App on Container Deploy: prizegen'
  inputs:
    azureSubscription: 'Free Trial (7f34fecc-80ca-417b-9aae-80ddc33a2d4b)'
    appName: prize
    imageName: 'elsahib20/przgen:$(Build.BuildId)'

- task: AzureFunctionAppContainer@1
  displayName: 'Azure Function App on Container Deploy: theprizeapp'
  inputs:
    azureSubscription: 'Free Trial (7f34fecc-80ca-417b-9aae-80ddc33a2d4b)'
    appName: theprizeapp
    imageName: 'elsahib20/prize:$(Build.BuildId)'
