version: "3.7"
services: 
    txtgen:
        build: ./txtgen
        ports: 
            - "8000:8000"
    numgen:
        build: ./numgen
        ports: 
            - "8001:8000"
    przgen:
        build: ./przgen
        depends_on: 
            - numgen
            - txtgen
        ports: 
            - "8002:8000"
    prize:
        build: ./prize
        depends_on: 
            - numgen
            - txtgen
            - przgen
        ports: 
            - "80:8000"
        environment:
            SECRET_KEY: ${SECRET_KEY}
            DATABASE_URI: ${DATABASE_URI}
            DBUser: ${DBUser}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            DBserv: ${DBserv}
        command: bash -c './chkDB.sh && gunicorn --workers=4 --bind=0.0.0.0:8000 app:app'